List<String> books = [
  'The Warlock of Firetop Mountain',
  'The Citadel of Chaos',
  'The Forest of Doom',
  'Starship Traveller',
  'City of Thieves',
  'Deathtrap Dungeon',
  'Island of the Lizard King',
  'Scorpion Swamp',
  'Caverns of the Snow Witch',
  'House of Hell',
  'Talisman of Death',
  'Space Assassin',
  'Freeway Fighter',
  'Temple of Terror',
  'The Rings of Kether',
  'Seas of Blood',
  'Appointment with F.E.A.R.',
  'Rebel Planet',
  'Demons of the Deep',
  'Sword of the Samurai',
  'Trial of Champions',
  'Robot Commando',
  'Masks of Mayhem',
  'Creature of Havoc',
  'Beneath Nightmare Castle',
  'Crypt of the Sorcerer',
  'Star Strider',
  'Phantoms of Fear',
  'Midnight Rogue',
  'Chasms of Malice',
  'Battleblade Warrior',
  'Slaves of the Abyss',
  'Sky Lord',
  'Stealer of Souls',
  'Daggers of Darkness',
  'Armies of Death',
  'Portal of Evil',
  'Vault of the Vampire',
  'Fangs of Fury',
  'Dead of Night',
  'Master of Chaos',
  'Black Vein Prophecy',
  'The Keep of the Lich-Lord',
  'Legend of the Shadow Warriors',
  'Spectral Stalkers',
  'Tower of Destruction',
  'The Crimson Tide',
  'Moonrunner',
  'Siege of Sardath',
  'Return to Firetop Mountain',
  'Island of the Undead',
  'Night Dragon',
  'Spellbreaker',
  'Legend of Zagor',
  'Deathmoor',
  'Knights of Doom',
  'Magehunter',
  'Revenge of the Vampire',
  'Curse of the Mummy',
];
